server:
  port: 8080

spring:
  application:
    name: cloud_gateway
  cloud:
    gateway:
      routes:
        - id: user_identity_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**

        - id: collaboration_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/groups/**,/api/v1/files/**

app:
  jwtSecret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
